// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Repositories.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int RequestedByUserId { get; set; }

    public DateOnly BookingDate { get; set; }

    public string Status { get; set; }

    public DateTime RequestedAt { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public DateTime? CancelAt { get; set; }

    [JsonIgnore]
    public virtual User RequestedByUser { get; set; }

    public virtual ICollection<Roomslot> Roomslots { get; set; } = new List<Roomslot>();
}