// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<Campus> Campuses { get; set; }

    public virtual DbSet<Room> Rooms { get; set; }

    public virtual DbSet<Roomslot> Roomslots { get; set; }

    public virtual DbSet<Slot> Slots { get; set; }

    public virtual DbSet<User> Users { get; set; }
    private string GetConnectionString()
    {
        IConfiguration configuration = new ConfigurationBuilder()
         .SetBasePath(Directory.GetCurrentDirectory())
         .AddJsonFile("appsettings.json", true, true).Build();
        return configuration["ConnectionStrings:DBDefault"];
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(GetConnectionString());
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("PK__BOOKINGS__73951AED4580CBDF");

            entity.ToTable("BOOKINGS");

            entity.Property(e => e.RequestedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.RequestedByUser).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.RequestedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Booking_User");

            entity.HasMany(d => d.Roomslots).WithMany(p => p.Bookings)
                .UsingEntity<Dictionary<string, object>>(
                    "Bookingroomslot",
                    r => r.HasOne<Roomslot>().WithMany()
                        .HasForeignKey("RoomId", "SlotId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_BRS_RoomSlot"),
                    l => l.HasOne<Booking>().WithMany()
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK_BRS_Booking"),
                    j =>
                    {
                        j.HasKey("BookingId", "RoomId", "SlotId").HasName("PK_BookingRoomSlots");
                        j.ToTable("BOOKINGROOMSLOT");
                    });
        });

        modelBuilder.Entity<Campus>(entity =>
        {
            entity.HasKey(e => e.CampusId).HasName("PK__CAMPUS__FD598DD6CDCE6740");

            entity.ToTable("CAMPUS");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<Room>(entity =>
        {
            entity.HasKey(e => e.RoomId).HasName("PK__ROOMS__328639394FF5FEE2");

            entity.ToTable("ROOMS", tb => tb.HasTrigger("trg_CreateRoomSlots"));

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.IsAvailable).HasDefaultValue(true);
            entity.Property(e => e.RoomType).HasMaxLength(100);

            entity.HasOne(d => d.Campus).WithMany(p => p.Rooms)
                .HasForeignKey(d => d.CampusId)
                .HasConstraintName("FK_Room_Campus");
        });

        modelBuilder.Entity<Roomslot>(entity =>
        {
            entity.HasKey(e => new { e.RoomId, e.SlotId }).HasName("PK_RoomSlots");

            entity.ToTable("ROOMSLOT");

            entity.HasOne(d => d.Room).WithMany(p => p.Roomslots)
                .HasForeignKey(d => d.RoomId)
                .HasConstraintName("FK_RoomSlots_Room");

            entity.HasOne(d => d.Slot).WithMany(p => p.Roomslots)
                .HasForeignKey(d => d.SlotId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoomSlots_Slot");
        });

        modelBuilder.Entity<Slot>(entity =>
        {
            entity.HasKey(e => e.SlotId).HasName("PK__SLOTS__0A124AAF24DF6AC1");

            entity.ToTable("SLOTS");

            entity.Property(e => e.EndTime).HasPrecision(0);
            entity.Property(e => e.StartTime).HasPrecision(0);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__USERS__1788CC4C93B156FD");

            entity.ToTable("USERS");

            entity.HasIndex(e => e.Email, "UQ__USERS__A9D10534ADD7335F").IsUnique();

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(500);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}