// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Repositories.Models;

public partial class Roomslot
{
    public int RoomId { get; set; }

    public int SlotId { get; set; }

    public virtual Room Room { get; set; }

    public virtual Slot Slot { get; set; }

    [JsonIgnore]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}