// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Repositories.Models;

public partial class Room
{
    public int RoomId { get; set; }

    public string Code { get; set; }

    public int? CampusId { get; set; }

    public string RoomType { get; set; }

    public int? Capacity { get; set; }

    public bool IsAvailable { get; set; }

    public virtual Campus Campus { get; set; }

    [JsonIgnore]
    public virtual ICollection<Roomslot> Roomslots { get; set; } = new List<Roomslot>();
}