// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Repositories.Models;

public partial class Slot
{
    public int SlotId { get; set; }

    public int SlotNumber { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    [JsonIgnore]
    public virtual ICollection<Roomslot> Roomslots { get; set; } = new List<Roomslot>();
}